### ISSUE TITLE
Performance issues with console sink

### ISSUE THREAD

**Issue by lisssy21** [serilog/serilog-sinks-console#58]
**A few questions before you begin:**

> Is this an issue related to the Serilog core project or one of the [sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks) or [community projects](https://github.com/serilog/serilog/wiki/Community-Projects).  This issue list is intended for Serilog core issues. If this issue relates to a sink or related project, please log on the related repository.  Please use [Gitter chat](https://gitter.im/serilog/serilog) and [Stack Overflow](http://stackoverflow.com/questions/tagged/serilog)  for discussions and questons.

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ /] Bug
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
3.1.1

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ /] netCore 2.0
- [ ] netCore 1.0
- [/ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behaviour you are experiencing?**
When we are using console sink, we realised there is a huge increase in cpu context switches even after using async. Our application is still suffering from performance issues. Setting minimum log level to INFO did not resolve the issue either. The only solution was to turn off console logging. In the long term, this is not the solution. We need console logs. I have a screenshot attached with the comparison between enabling and disabling console logging. All logging means enabling both console and file sinks. 
![IMG_20190414_152639](https://user-images.githubusercontent.com/49437005/56089752-4ffe9580-5eca-11e9-878f-79eb908fa0ec.jpg)
Not sure what's wrong with console sink but i hope some expert can help us with this issue.
Log4net did not cause such performance issue previously, we hope we dont make a mistake by migrating over to Serilog.

**Please describe the expected behaviour if the ?**
Lower context switches when using console sink as logger, just like file sink. There is no issue when using file sink

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
*NOTE: A small code sample goes a long way in expediting bug fixes or illustrating an enhancement you are proposing.*
Create a serilog logger with both console and file sink. Call logger and write log messages multiple times in a second. (our application has a high load of processes running with many log messages at the same time). Check in process explorer - columns for the context switches and context switch delta. Compare it with and without console logging

**Comment by skomis-mm** [comment]
Hi, @lisssy21 . 
If you on Windows 10/Windows Server 2016+ or on Linux, try to specify any *AnsiConsoleTheme*-based theme.
- otherwise, if you **can't** use *AnsiConsoleTheme* theme and you run application locally but you plan to run this app as a service on production then don't bother much - as background service it should run without issues you see.
  - otherwise, if you **do** need to run it as console with UI on production but don't need coloring there then try to specify *ConsoleTheme.None* in production config.
    - otherwise, if you **do** need coloring on production then...I think there are not much options left, unfortunately :)

By default, it uses *SystemConsoleTheme*-based theme. (Literate, see https://github.com/serilog/serilog-sinks-console)
I did some profiling and indeed it slow because of many little system calls to set/reset colors and writes within the single message. But since Serilog is structured-first logger framework, it is kinda expected because you need to color every captured entity in the message differently.
I can imaging that log4net does not have such issues because the coloring are per-line based so there are not much calls to the underlying Console.
*AnsiConsoleTheme*-based themes are utilize the fact that you can specify colors and controls in the string itself via codes so its really fast in comparison with the standard coloring console API.

In Serilog console (especially colored console) sink is really not the most important one and helpful usually for development only because of its readability. And in the production you use more tailored sinks like *Seq*, *Elasticsearch*, *ApplicationInsights* etc to get the most out from the structured logging.

Hope this helps.

**Comment by nblumhardt** [comment]
Closing with the recommendation that `AnsiConsoleTheme.*` or `ConsoleTheme.None` is used if perf requirements demand it.

**Comment by EricStG** [comment]
Just FYI, we use the console sink with the compact json formatter for our docker apps, so it might be worth documenting somewhere since I doubt that we're the only ones.

**Comment by nblumhardt** [comment]
@EricStG _CompactJsonFormatter_ won't engage the theming mechanism here, so this issue shouldn't apply in your situation. HTH!
