### ISSUE TITLE
Can we make OutputTemplateRenderer public?

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-sinks-console#68]
https://github.com/serilog/serilog-sinks-console/blob/7737b6d3270432f63005d2ab30af90b4b82aaa18/src/Serilog.Sinks.Console/Sinks/SystemConsole/Output/OutputTemplateRenderer.cs#L26

I am trying to write my own Sink that falls back on all the console stuff but I cant get to classes like these.

**Comment by nblumhardt** [comment]
Hi Victorio, thanks for the note!

I think this is one that could be considered - it seems to be a nice narrow implementation of `ITextFormatter`, so exposing it (perhaps as `ThemedOutputTemplateTextFormatter` or something similarly descriptive?) seems low-risk.

Can you sketch a bit about your sink/scenario, so we can figure out why using this class directly (instead of just wrapping up an instance of the console sink) is needed? Thanks!

**Comment by VictorioBerra** [comment]
I hadn't actually considered wrapping up the instance. My use case is I want to keep a rolling static list of messages. I ended up rolling my own sink and using serilog compact to format it as JSON and store that as a list of strings.

**Comment by nblumhardt** [comment]
Great, glad you were able to get something working. I think you may have been looking for [`MessageTemplateTextFormatter`](https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs#L33) - it's public, and mostly equivalent to the themed one used within the console sink.

**Comment by VictorioBerra** [comment]
I appreciate the quick help!
